<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Philiprehberger.CreditCardValidator</RootNamespace>

    <PackageId>Philiprehberger.CreditCardValidator</PackageId>
    <Version>0.1.1</Version>
    <Authors>Philip Rehberger</Authors>
    <Description>Validate credit card numbers with Luhn check, detect card brand, and mask for display.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>credit-card;validation;luhn;payment;e-commerce</PackageTags>
    <RepositoryUrl>https://github.com/philiprehberger/dotnet-credit-card-validator</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
